export const LOGUEO = 'LOGUEO'
export const USUARIOREGISTRADO = 'USUARIOREGISTRADO'
export const CERRARUSUARIO = 'CERRARUSUARIO'
export const ACTUALIZARUSUARIO = 'ACTUALIZARUSUARIO'


//!Lineup
export const LINEUP = 'LINEUP'
export const LISTAJUEGOS = 'LISTAJUEGOS'