export const juegos = [
    {
        cont: 1,
        campeonato: 'Liga Nacional 2024',
        equipoLocal: 'Tigres del Norte',
        equipoVisitante: 'Águilas Doradas',
        fechaJuego: '2024-01-15',
        carrerasLocal: 5,
        carrerasVisitante: 3,
        estado: 'Activo', // Puede ser "Activo" o "Finalizado"
    },
    {
        cont: 2,
        campeonato: 'Liga Nacional 2024',
        equipoLocal: 'Leones del Sur',
        equipoVisitante: 'Halcones Negros',
        fechaJuego: '2024-01-16',
        carrerasLocal: 7,
        carrerasVisitante: 8,
        estado: 'Finalizado',
    },
    {
        cont: 3,
        campeonato: 'Copa Internacional',
        equipoLocal: 'Estrellas Rojas',
        equipoVisitante: 'Toros Salvajes',
        fechaJuego: '2024-02-10',
        carrerasLocal: 6,
        carrerasVisitante: 2,
        estado: 'Activo',
    },
    {
        cont: 4,
        campeonato: 'Copa Internacional',
        equipoLocal: 'Águilas Doradas',
        equipoVisitante: 'Tigres del Norte',
        fechaJuego: '2024-02-11',
        carrerasLocal: 4,
        carrerasVisitante: 4,
        estado: 'Finalizado',
    },
    {
        cont: 5,
        campeonato: 'Liga Nacional 2024',
        equipoLocal: 'Halcones Negros',
        equipoVisitante: 'Leones del Sur',
        fechaJuego: '2024-03-05',
        carrerasLocal: 10,
        carrerasVisitante: 9,
        estado: 'Activo',
    },
    {
        cont: 6,
        campeonato: 'Liga Nacional 2024',
        equipoLocal: 'Toros Salvajes',
        equipoVisitante: 'Estrellas Rojas',
        fechaJuego: '2024-03-06',
        carrerasLocal: 3,
        carrerasVisitante: 5,
        estado: 'Finalizado',
    },
    {
        cont: 7,
        campeonato: 'Copa Internacional',
        equipoLocal: 'Tigres del Norte',
        equipoVisitante: 'Leones del Sur',
        fechaJuego: '2024-04-15',
        carrerasLocal: 5,
        carrerasVisitante: 7,
        estado: 'Activo',
    },
    {
        cont: 8,
        campeonato: 'Copa Internacional',
        equipoLocal: 'Águilas Doradas',
        equipoVisitante: 'Estrellas Rojas',
        fechaJuego: '2024-04-20',
        carrerasLocal: 8,
        carrerasVisitante: 6,
        estado: 'Finalizado',
    },
    {
        cont: 9,
        campeonato: 'Liga Nacional 2024',
        equipoLocal: 'Halcones Negros',
        equipoVisitante: 'Toros Salvajes',
        fechaJuego: '2024-05-10',
        carrerasLocal: 9,
        carrerasVisitante: 3,
        estado: 'Activo',
    },
    {
        cont: 10,
        campeonato: 'Liga Nacional 2024',
        equipoLocal: 'Leones del Sur',
        equipoVisitante: 'Águilas Doradas',
        fechaJuego: '2024-05-15',
        carrerasLocal: 4,
        carrerasVisitante: 8,
        estado: 'Finalizado',
    }
];