export const usuarios = [
    {
        cont: 1,
        idusuario: '106758454',
        nombre: 'Luis Alberto',
        papellido: 'Buelvas',
        sapellido: 'Cogollo',
        fechanacimiento: '1990-05-15',
        numerocamisa: '10',
        nivel: 'fuerte',
        averaje: 0,
        imagen: 'https://res.cloudinary.com/dss2hdisa/image/upload/images_ykicww.jpg'
    },
    {
        cont: 2,
        idusuario: '10000002',
        nombre: 'Andres Javier',
        papellido: 'Peña',
        sapellido: 'Lopez',
        fechanacimiento: '1992-08-25',
        numerocamisa: '9',
        nivel: 'novato',
        averaje: 0,
        imagen: 'https://res.cloudinary.com/dss2hdisa/image/upload/png-transparent-bowser-mario-bros-new-super-mario-bros-mario-kart-wii-bowser-super-mario-bros-video-game-mario-kart-double-dash_hkentb.png'
    },
    {
        cont: 3,
        idusuario: '10000003',
        nombre: 'Angela Maria',
        papellido: 'Orozco',
        sapellido: 'Ramirez',
        fechanacimiento: '1995-12-10',
        numerocamisa: '7',
        nivel: 'regular',
        averaje: 0,
        imagen: 'https://res.cloudinary.com/dss2hdisa/image/upload/Toadette_Super_Mario_Bros._Wonder_yd1dop.webp'
    },
    {
        cont: 4,
        idusuario: '10000004',
        nombre: 'Carlos Eduardo',
        papellido: 'Gomez',
        sapellido: 'Martinez',
        fechanacimiento: '1988-07-03',
        numerocamisa: '11',
        nivel: 'fuerte',
        averaje: 0,
        imagen: 'https://res.cloudinary.com/dss2hdisa/image/upload/Lemmy_Koopa_NSMBU_artwork_yzanue.webp'
    },
    {
        cont: 5,
        idusuario: '10000005',
        nombre: 'Maria Fernanda',
        papellido: 'Lopez',
        sapellido: 'Vega',
        fechanacimiento: '1994-02-17',
        numerocamisa: '6',
        nivel: 'novato',
        averaje: 0,
        imagen: 'https://res.cloudinary.com/dss2hdisa/image/upload/170px-Mpsrart28_cti3iu.webp'
    },
    {
        cont: 6,
        idusuario: '10000006',
        nombre: 'Juan Pablo',
        papellido: 'Martinez',
        sapellido: 'Diaz',
        fechanacimiento: '1991-04-30',
        numerocamisa: '8',
        nivel: 'regular',
        averaje: 0,
        imagen: 'https://res.cloudinary.com/dss2hdisa/image/upload/Lakitu_NSMBU_wej4bp.webp'
    },
    {
        cont: 7,
        idusuario: '10000007',
        nombre: 'Sofia Isabel',
        papellido: 'Ramirez',
        sapellido: 'Hernandez',
        fechanacimiento: '1993-06-20',
        numerocamisa: '5',
        nivel: 'novato',
        averaje: 0,
        imagen: 'https://res.cloudinary.com/dss2hdisa/image/upload/gratis-png-mario-bros-bowser-mario-party-5-mario-party-8-mario-bros_voet1j.png'
    },
    {
        cont: 8,
        idusuario: '10000008',
        nombre: 'Alejandro Javier',
        papellido: 'Martinez',
        sapellido: 'Perea',
        fechanacimiento: '1990-09-10',
        numerocamisa: '4',
        nivel: 'fuerte',
        averaje: 0,
        imagen: 'https://res.cloudinary.com/dss2hdisa/image/upload/Goomba_29_mzpppt.webp'
    },
    {
        cont: 9,
        idusuario: '10000009',
        nombre: 'Laura Carolina',
        papellido: 'Gonzalez',
        sapellido: 'Suarez',
        fechanacimiento: '1996-03-08',
        numerocamisa: '12',
        nivel: 'regular',
        averaje: 0,
        imagen: 'https://res.cloudinary.com/dss2hdisa/image/upload/fdba36d6d0f4a1699dcc39ff4c0df3a0_hsonlt.jpg'
    },
    {
        cont: 10,
        idusuario: '10000010',
        nombre: 'Pedro Antonio',
        papellido: 'Hernandez',
        sapellido: 'Castro',
        fechanacimiento: '1992-12-01',
        numerocamisa: '15',
        nivel: 'novato',
        averaje: 0,
        imagen: 'https://res.cloudinary.com/dss2hdisa/image/upload/f592cfcbf86e8c8fefe38506b835d62c_hapbyc.jpg'
    },
    {
        cont: 11,
        idusuario: '10000011',
        nombre: 'Jose Luis',
        papellido: 'Ruiz',
        sapellido: 'Perez',
        fechanacimiento: '1990-07-15',
        numerocamisa: '3',
        nivel: 'fuerte',
        averaje: 0,
        imagen: 'https://res.cloudinary.com/dss2hdisa/image/upload/enhanced-buzz-wide-873-1424632151-6_ifxntb.webp'
    },
    {
        cont: 12,
        idusuario: '10000012',
        nombre: 'Carolina Isabel',
        papellido: 'Perez',
        sapellido: 'Lozano',
        fechanacimiento: '1994-01-05',
        numerocamisa: '14',
        nivel: 'novato',
        averaje: 0,
        imagen: 'https://res.cloudinary.com/dss2hdisa/image/upload/enhanced-buzz-wide-21469-1424631443-4_qhzzjq.webp'
    },
    {
        cont: 13,
        idusuario: '10000013',
        nombre: 'Martha Lucia',
        papellido: 'Diaz',
        sapellido: 'Martinez',
        fechanacimiento: '1995-11-22',
        numerocamisa: '13',
        nivel: 'regular',
        averaje: 0,
        imagen: 'https://res.cloudinary.com/dss2hdisa/image/upload/enhanced-buzz-19527-1424630230-7_f2eopc.webp'
    },
    {
        cont: 14,
        idusuario: '10000014',
        nombre: 'Juan Camilo',
        papellido: 'Guzman',
        sapellido: 'Torres',
        fechanacimiento: '1989-05-10',
        numerocamisa: '16',
        nivel: 'fuerte',
        averaje: 0,
        imagen: 'https://res.cloudinary.com/dss2hdisa/image/upload/c9f84c9c0c8116222bdbceab78ff2e55_cm723w.jpg'
    },
    {
        cont: 15,
        idusuario: '10000015',
        nombre: 'Valeria Eugenia',
        papellido: 'Suarez',
        sapellido: 'Ruiz',
        fechanacimiento: '1992-02-18',
        numerocamisa: '18',
        nivel: 'novato',
        averaje: 0,
        imagen: 'https://res.cloudinary.com/dss2hdisa/image/upload/b5f560e611a7a2e4aa8ab006c093be20_xsegt1.png'
    },
    {
        cont: 16,
        idusuario: '10000016',
        nombre: 'Felipe Andres',
        papellido: 'Lozano',
        sapellido: 'Gomez',
        fechanacimiento: '1993-09-23',
        numerocamisa: '19',
        nivel: 'regular',
        averaje: 0,
        imagen: 'https://res.cloudinary.com/dss2hdisa/image/upload/descarga_ire3pf.jpg'
    },
    {
        cont: 17,
        idusuario: '10000017',
        nombre: 'Santiago',
        papellido: 'Ocampo',
        sapellido: 'Martinez',
        fechanacimiento: '1994-11-02',
        numerocamisa: '20',
        nivel: 'fuerte',
        averaje: 0,
        imagen: 'https://res.cloudinary.com/dss2hdisa/image/upload/aca9156a9bd866f2a9e14cc16ee0d3946faab00ar1-512-339v2_hq_if18eb.jpg'
    },
    {
        cont: 18,
        idusuario: '10000018',
        nombre: 'Johana Marcela',
        papellido: 'Torres',
        sapellido: 'Lopez',
        fechanacimiento: '1996-04-25',
        numerocamisa: '17',
        nivel: 'novato',
        averaje: 0,
        imagen: 'https://res.cloudinary.com/dss2hdisa/image/upload/88c11f4810c71b37e8952d8f927c26b4_dbr561.jpg'
    },
    {
        cont: 19,
        idusuario: '10000019',
        nombre: 'Rafael Alejandro',
        papellido: 'Lopez',
        sapellido: 'Serrano',
        fechanacimiento: '1991-03-15',
        numerocamisa: '21',
        nivel: 'regular',
        averaje: 0,
        imagen: 'https://res.cloudinary.com/dss2hdisa/image/upload/Builder_Toadette_Play_xt9b8u.webp'
    },
    {
        cont: 20,
        idusuario: '10000020',
        nombre: 'Isabel Cristina',
        papellido: 'Gomez',
        sapellido: 'Lozano',
        fechanacimiento: '1990-08-17',
        numerocamisa: '22',
        nivel: 'fuerte',
        averaje: 0,
        imagen: 'https://res.cloudinary.com/dss2hdisa/image/upload/d3b01e04974c3450695f0ca4df2ab0bb_dvirh6.jpg'
    }
];
